### ISSUE TITLE
New domogik user rights

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik-installation#1]
Test script on Debian Jessie (8.7).
Nothing is installed on this Vm, only one user has been created

Some non-critical messages I think, during installation:

    Running test_config.py...

     [ Start to test configuration ]
     ...
     [ Parse [database] section ]
    ==> No module named pytz

...

    [       ]--------------------------------------------------------------------------------------------------------------------------------
    [       ]        Install the pip dependencies for the Domoweb package
    [       ]--------------------------------------------------------------------------------------------------------------------------------
    [ INFO  ] Running : 'cd /opt/dmgtest/domoweb/ && pip install -r requirements.txt' ...
    You must give at least one requirement to install (see "pip help install")
    [ OK    ] ... ok

I have some issue with domogik user and the end of installation:

    [       ]--------------------------------------------------------------------------------------------------------------------------------
    [       ]        Install packages...
    [       ]--------------------------------------------------------------------------------------------------------------------------------
    -su: 1: dmg_package: Permission denied
    [ INFO  ] Installing the package 'plugin_weather' from url 'http://github.com/fritz-smh/domogik-plugin-weather/archive/master.zip'...
    Pas de répertoire, connexion avec HOME=/
    -su: 1: dmg_package: Permission denied
    [ ERROR ] Error while installing the package 'plugin_weather' from url 'http://github.com/fritz-smh/domogik-plugin-weather/archive/master.zip'
    [ ABORT ] The installation is aborted due to the previous error!
    dan@hermes:~$

    root@hermes:~# /usr/local/bin/dmg_package
    ERROR : this Domogik tool must be run with the user defined in /etc/default/domogik as DOMOGIK_USER : domogik

    root@hermes:~# su - domogik
    Pas de répertoire, connexion avec HOME=/
    $ dmg_package
    -su: 1: dmg_package: Permission denied

    root@hermes:~# l /usr/local/bin/dmg_package
    -rwxr-x--- 1 root staff 309 mai   19 00:34 /usr/local/bin/dmg_package*

I add domogik user in staff group to be able to execute dmg_package:

    root@hermes:~# adduser domogik staff
    Ajout de l'utilisateur « domogik » au groupe « staff »...
    Ajout de l'utilisateur domogik au groupe staff
    Fait.

But there is another error with domogik directory rights:

    domogik@hermes:/$ /usr/local/bin/dmg_package --help
    Traceback (most recent call last):
      File "/usr/local/bin/dmg_package", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
        @_call_aside
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 646, in _build_master
        ws = cls()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 639, in __init__
        self.add_entry(entry)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 695, in add_entry
        for dist in find_distributions(entry, True):
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2012, in find_on_path
        if len(os.listdir(fullpath)) == 0:
    OSError: [Errno 13] Permission denied: '/opt/dmgtest/domogik/src/Domogik.egg-info'

    domogik@hermes:/$ ls -l /opt/dmgtest/domogik/src
    total 8
    drwxrwxr-x 13 root root 4096 mai   19 00:14 domogik                    <== root
    drwxr-x---  2 root root 4096 mai   19 00:14 Domogik.egg-info        <== root

**Comment by fritz-smh** [comment]
Thanks for the test, I will have a look.

Not sure if you did it, but a good idea is to create a snapshot on the
fresh vm before testing the installer ;). So the rollback is easy for some
more tests

**Comment by fritz-smh** [comment]
one more question : is this a virtualbox image ?

**Comment by vdomos** [comment]
I use vagrant with virtualbox.
it use a Vagrantfile like docker.

I make a personnal Debian/jessie image and with few command it's more simple to use VM:

   vagrant up (create VM or run VM if yes)
   vagrant ssh (connect)
   vagrant destroy
